### ISSUE TITLE
Recommended ways to encode various COVID-19 vaccinations

### ISSUE THREAD

**Issue by Mr0grog** [smart-on-fhir/smart-scheduling-links#13]
In a3b82274bbb0c247a11b6739d2644c56ed0d3be8, required service type codings were established for COVID-19 vaccinations, but I realized as I was digging in more today that these aren’t very specific.

Are there any recommendations as to how publishers should code:
- First vs. second dose (for vaccine types where that’s applicable)
- Type of vaccine (e.g. Pfizer/Moderna/Janssen)

Or are codings even the best place to do this? Should these be extensions on slots? (Or something else I’m not thinking of?)

**Comment by jmandel** [comment]
Totally agree! My sense is we'll want to define a standard way to convey schedule information like "Appointments for {{Product X}} {{Dose Y}}". These could be more detailed Schedule.serviceType codes, or they could be extensions on the Schedule, or they could even be represented on slots -- but my sense is that Schedule is probably the better place to represent these because it corresponds best to the clinical workflow (e.g., if an immunization site wants to schedule certain appointments in slightly longer slots, to make time for activities like verifying history of a previous dose).
