### ISSUE TITLE
Handling waitlists

### ISSUE THREAD

**Issue by Mr0grog** [smart-on-fhir/smart-scheduling-links#14]
Many of the vaccine providers in states I’m working with require people to sign up for a waitlist rather than book immediately. Having slot information might still be useful when somebody’s been on the waitlist and it’s their turn, but when people first encounter a provider that uses a waitlist, it would be useful to have a standard, structured way to represent that in the data (so we can show a different call to action, for example).

The waitlist signup might have also have a different URL than the booking URL (practically speaking, I think this will be rare since we often don’t even have deep booking links right now, but who knows what the future will hold!).

**Comment by jmandel** [comment]
I like this point -- this would be, perhaps, a way for Locations to advertise something like "Even though I don't have any slots or schedule to advertise, I do have a place you can go to put your name on a wait list"? We might represent that as an extension on Location, or even (if we're really going to embrace FHIR's extensibility model) an extension on `Location.telecom`, which would look something like:

```json
{
  "resourceType": "Location",
  "id": "123",
  "telecom": [{
    "system": "phone",
    "value": "413-000-0000"
  }, {
    "system": "url",
    "value": "https://pharmacy.example.com",
  }, {
    "system": "url",
    "value": "https://pharmacy.example.com/wait-list/signup.php?LocId=GvvZO",
    "extension": [{
      "url": "http://fhir-registry.smarthealthit.org/StructureDefinition/telecom-type",
      "code": "wait-list-url"
    }]
  }],
}

```

**Comment by Mr0grog** [comment]
Oh, that’s neat! I think the thing that might be missing here is whether the waitlist is *required*. 

For example, the most common scenario I’ve seen is that a location requires you to get on the waitlist first, and then once it’s your turn, you have N hours to book one of the free appointment slots. If a provider like that isn’t publishing slot availability publicly, then this is straightforward (no slots + waitlist in telecom array = "show the waitlist signup CTA"), but if they are publishing slots at the same time (to support people who’s turn it is to sign up), then we need a way to identify that someone *has* to sign up for the waitlist, rather than that it’s an option. (I suppose this the info about it being required could also be in the description; but that affords fewer clever design decisions.)

Also, is the location the right level for this? As long as we’re always talking COVID-19 (which I think we are, in the short term) that makes sense, but the spec reads to me like it’s designed for a longer future beyond this pandemic, and it seems like this kind of thing might be a schedule-level concern rather than a location-level one.

**Comment by jmandel** [comment]
Good point on the location-vs-Schedule question about where this belongs, given the goals of the spec to support a broader set of use cases. From that perspective, an extension on Schedule is a better fit (I had initially assumed there were no Schedules or Slots in this use case, but of course we could require a Schedule even if we don't require slots.)

I don't fully understand the model you have in mind -- would a waitlist-gated vaccine clinic really publish a public set of slots even though only "arrived-at-the-top-of-the-waitlist" patients would be allowed to book? I would have assumed in those scenarios that the waitlisted site would just have its own booking tool advertising options in their "your turn! hurry and book!" email. (That said, I certainly wouldn't want to prohibit or discourage publication of slots, but conveying the semantics of who's allowed to book gets challenging. I guess we should call out the connection to #17 because "only available for patients after they get to the top of the waitlist" is a kind of restriction :-))

**Comment by Mr0grog** [comment]
>  would a waitlist-gated vaccine clinic really publish a public set of slots even though only "arrived-at-the-top-of-the-waitlist" patients would be allowed to book?

Yes! New Jersey’s state-operated system is a perfect example of this. (It may just be how Microsoft VRAS works; I’m not sure.) For example, this map shows locations with appointments, but unless you land on the page with a special token in the URL, you get rejected when you click the “book appointment” button: https://covidvaccine.nj.gov/covidvaccine-location-map/

(More broadly, some states are using the same data being collected for this public appointment availability info to support their call centers, who are often helping those with accessibility or technology issues book their appointment. Having the appointment slots available even when the general public can’t register is a game-changer for them — this setup has let them book people they haven’t been able to before.)

**Comment by Mr0grog** [comment]
> conveying the semantics of who's allowed to book gets challenging.

Very. :)

**Comment by Mr0grog** [comment]
FWIW, figuring out how to bifurcate data flows into a more- and less- privileged path is definitely another way to do this; it’s just a lot more complex than what we’re doing in some places right now, and doesn’t seem like some systems (e.g. VRAS) will do. But we are sort of sitting in front of those, so it’s not necessarily a huge deal. 🤷

**Comment by jmandel** [comment]
Cool, that detail is a big help. So the minimum steps here might be:

* Add an extension on Schedule like "booking-requirement" where the values are valueCoding
* Define Codings for common known booking restrictions (including: "wait-list invitees only")
* Document that clients should be on the lookout for these restrictions and if a Schedule includes the "wait-list invitees only" restriction, clients should not include this location's slots in a general search result, or should otherwise highlight the restrictions appropriately

**Comment by Mr0grog** [comment]
That makes a lot of sense to me! So we’d have something like:

```js
{
  "resourceType": "Schedule",
  "extension": [
    {
      "url": "http://some.url/for/booking-requirement",
      "valueCoding": {
        "system": "http://some.url/for/booking-requirement/system",
        "code": "wait-list invitees only"
      }
    },
    {
      "url": "http://some.url/for/booking-requirement",
      "valueCoding": {
        "system": "http://some.url/for/booking-requirement/system",
        "code": "county residents only"
      }
    }
  ]
}
```

Or…

```js
{
  "resourceType": "Schedule",
  "extension": [
    {
      "url": "http://some.url/for/booking-requirement",
      "valueCode": "wait-list invitees only"
    },
    {
      "url": "http://some.url/for/booking-requirement",
      "valueCode": "county residents only"
    },
  ]
}
```

(I’m getting a little mixed up between codes and codings; I probably need to find time to read that part of the spec in detail.)

Is there a useful way to make that any less verbose? It doesn’t seem like it, but if there were a way to make the value an array:

```js
{
  "resourceType": "Schedule",
  "extension": [
    {
      "url": "http://some.url/for/booking-requirement",
      "valueCode": [
        "wait-list invitees only",
        "county residents only"
      ]
    },
  ]
}
```

**Comment by jmandel** [comment]
Yeah, your two examples (`valueCoding` and `valueCode`) are right. There's a slight preference for `valueCoding` because it allows sites to define their own codes, rather than trying to pre-specify every allowable value.

> Is there a useful way to make that any less verbose?

Alas, I file this in the category of "standards tax" -- providing an extension with cardinality >1 in FHIR means repeating the extension :/ (On the plus side, there's slight consolation in the fact that the schema is regular and you never have to "worry" about dealing with values in a given slot that are sometimes-arrays-and-sometimes-not.)

**Comment by Mr0grog** [comment]
> There's a slight preference for `valueCoding` because it allows sites to define their own codes

Ah, I see the note about the values for `code` being fixed! The differentiation makes a little more sense now. :)

👍

**Comment by jmandel** [comment]
Going to close this to consolidate discussion in https://github.com/smart-on-fhir/smart-scheduling-links/issues/17
