### ISSUE TITLE
Indicating last updated times for individual objects

### ISSUE THREAD

**Issue by Mr0grog** [smart-on-fhir/smart-scheduling-links#16]
The only place timestamps for data freshness are clearly called out in the data is `transactionTime` on the manifest. In practice, individual slots, locations, and probably schedules may all have different “last updated” times (especially if data is pre-generated and published on a schedule, rather than in response to a request).

Is the best way to represent update times with the `meta` property, or is there another, more ideal way to do this?

I *think* the correct FHIR syntax for `meta` would be:

```js
{
  "meta": {
    "lastUpdated": "2021-03-15T23:00:01Z"
  },
  "resourceType": "Location",
  "id": "123",
  // etc...
}
```

**Comment by jmandel** [comment]
Within a given FHIR resource, you've got this right -- any resource can advertise its last updated time using this pattern. I'm not totally clear on how a client should use this or whether we should expect/encourage publishers to include it (but it's certainly OK for publishers to include this kind of information, and .meta.lastUpdated is the right way to convey it).

Can you say more about when a client would use lastUpdated-based logic rather than wholesale replacing its contents? Maybe you're thinking about situations like advertising "new slots just arrived" or "a new location just came online in your area"? My sense is that clients can build this sort of behavior even if they manage their own timestamps (and unless we *require* publishers to include this metadata, clients who want this behavior will need to manage their own timestamps to deal with publishers that don't support this pattern).

**Comment by jmandel** [comment]
Two more-or-less random comments:

* Even though FHIR JSON doesn't impose any rules on property order, it's typical to write `resourceType` and `id` before `meta`, and some FHIR parsers are optimized for this case (where `resourceType` is the first property)
* You may want to join the public chat at https://chat.fhir.org/#narrow/stream/281612-smart.2Fscheduling-links -- I'll advertise this better on the repo!

**Comment by Mr0grog** [comment]
> Can you say more about when a client would use lastUpdated-based logic rather than wholesale replacing its contents? Maybe you're thinking about situations like advertising "new slots just arrived" or "a new location just came online in your area"?

Ah, no, this is more about the opposite — being clear about when information might be out of date (although that’s a nice use-case, too).

This is one is likely more about *states* as aggregate publishers than individual clinics/pharmacies: since we are aggregating info from a variety of sources, we are usually getting updates from those sources on different schedules with different levels of freshness. More importantly, something might break (either on our side or theirs) with one source, and it’s important that we indicate the data for a given source isn’t very fresh. Saying there were available appointments 2 minutes ago is really different from saying there were available appointments 2 hours ago. 😉

It would be great to get this from “primary” publishers posting data about their own slots, but I think we can *mostly* assume that data will be reasonably up-to-date and its freshness will be the same across the dataset when we request it. (If the publisher has a scheduled job for publishing and that job stops or crashes, I suppose timestamps might help indicate that the source data is also stale. But that wouldn’t leave different resource-level update times and wasn’t my primary concern here.)

> Even though FHIR JSON doesn't impose any rules on property order, it's typical to write resourceType and id before meta, and some FHIR parsers are optimized for this case (where resourceType is the first property)

Good to know.

**Comment by jmandel** [comment]
Awesome. Client awareness about when things are getting stale makes a lot of sense -- but I will note that in this scenario, clients don't have a way to distinguish between "stale" (i.e. "hasn't been checked recently") vs "stable" (i.e.,
"hasn't changed recently").

The semantics of "lastUpdated" are about stability rather than staleness; lastUpdated should only change when the data are actually... updated.

If you're aggregating slots from multiple individual Scheduling Links providers into a combined Scheduling Links provider... you are probably in the business of remapping resource IDs, at least (because you can't be sure that Source A and Source B haven't both got something they call "Location/1" or "Slot/5"). While you are processing these inputs, you could also populate something like a "currentAsOf" extension with these specific semantics; or you could slightly abuse the semantics of lastUpdated and just populate it for this purpose.

**Comment by jmandel** [comment]
BTW with https://chat.fhir.org/#narrow/stream/179166-implementers/topic/currentAsOf.20extension.3F I've talked myself into believing that an aggregator "abusing" lastUpdated for this purpose is just fine :-)

**Comment by jmandel** [comment]
Current best recommendation:

* Explicit extension with `lastRetrieved` -- and if we put this extension on meta, it need not affect lastUpdated. (So, lastUpdated can continue to reflect the actual time of last change to the resource content)

**Comment by Mr0grog** [comment]
> The semantics of "lastUpdated" are about stability rather than staleness; lastUpdated should only change when the data are actually... updated.

Ahhhhhh, I saw the field name and completely skipped over the definition in the spec: “this value changes each time the content of the resource changes.” D'oh!

**Comment by jmandel** [comment]
I'm going to mark this as an "answered question" for now; down the line if we want to standardize how aggregators convey this, we can add these considerations to the spec.

**Comment by jmandel** [comment]
FHIR-I agreed to add a core extension as:

`http://hl7.org/fhir/StructureDefinition/lastSourceSync`

for use on Resource.meta.extension

**Comment by Mr0grog** [comment]
So, for example, we’d have records like:

```js
{
  "resourceType": "Slot",
  "meta": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/lastSourceSync",
        "valueDateTime": "2021-03-15T23:00:01Z"
      }
    ]
  },
  "id": "123",
  // etc...
}
```

?
