### ISSUE TITLE
Should we solidify state/jurisdiction-based discovery?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-scheduling-links#5]
Right now we say in https://github.com/smart-on-fhir/smart-scheduling-links/blob/master/specification.md#performance-considerations:

> Slot Publishers MAY choose to host a separate manifest file for each state or geographical region where they operate, if they want to make data independently available for clients with limited regions of interest.

If helping clients discover availability within a state is a key use case, should we establish a stronger convention?  Two ideas here for discussion...

### Separate manifest per jurisdiction
Slot Publishers SHOULD publish a separate manifest file for each state, with the naming convention of `[base]/[state]/$bulk-publish` (e.g., `[base]/MA/$bulk-publish`)

### One manifest with tagged entries
Slot Publisher SHOULD publish a single manifest but decorate manifest entries with a list of states that they cover, like:

```
"output": [{
      {
      "type": "Schedule",
      "url": "https://example.com/data/schedule_file_1.ndjson",
      "extension": {
        "jurisdiction": ["MA"]
      }
    },
    {
      "type": "Location",
      "url": "https://example.com/data/location_file_1.ndjson",
      "extension": {
        "jurisdiction": ["MA"]
      }
    },
    {
      "type": "Slot",
      "url": "https://example.com/data/slot_file_MA.ndjson",
      "extension": {
        "jurisdiction": ["MA"]
      }
    },
    {
      "type": "Slot",
      "url": "https://example.com/data/slot_file_NEARBY.ndjson",
      "extension": {
        "jurisdiction": ["CT", "RI", "NY", "VT"]
      }
    },
}]
```

**Comment by cooperthompson** [comment]
I like the option for one manifest file with the jurisdiction tags.  It will apply more naturally to international domains.

**Comment by jmandel** [comment]
I'm happy to give option (2) a shot; will note that other tags can be used, also.

**Comment by jmandel** [comment]
@cooperthompson would love a quick review on #6

**Comment by gotdan** [comment]
I like the tagged entry approach as well since it’s less reliant on external documentation (for example, to determine that slots are now available in an additional state). 

One thought - would it be worth adding a jurisdictionType field as well to support future use cases that want to segment schedule data  by things other than state (e.g., a set of zip codes)?

**Comment by brettmarquard** [comment]
What about specific fields for 'state' and 'zip'? In addition to generic string array

**Comment by jmandel** [comment]
I was thinking that jurisdictions would initially be at the level of states) territories; rather than adding separate "type"' indicators on a jurisdiction object,  I might rather do one of the following:

* Create sibling extensions next to jurisdiction as new use cases arise
* Rename `jurisdiction` to a generic `tag[]` array of FHIR codings, where the "system" could effectively act as a type when desired (or omitted)

**Comment by jmandel** [comment]
@brettmarquard has proposed taking option 2 but using the word "state" instead of "jurisdiction", which is fine by me (as long as we add a note that these don't need to be literal US states, but that territories etc count too -- [as FHIR says, state would be a "Sub-unit of country"](http://hl7.org/fhir/datatypes-definitions.html#Address.state).

@cooperthompson any concerns with this?

**Comment by gotdan** [comment]
@brettmarquard 's proposal to rename "jurisdiction" to "state" makes sense to me since it removes the need to define jurisdiction into state for this use case, and supports the addition of sibling extensions for things like zipcode down the line. 

I like the cleanliness of an array of coding from a theoretical perspective, but since use cases would have to define the systems they want clients to expect anyway, you kind of get this with less complexity through additional extensions.

**Comment by jmandel** [comment]
OK, I'll make this update and call it ready to go.
