### ISSUE TITLE
Consider loosening the VTrckS PIN identifier requirement

### ISSUE THREAD

**Issue by cooperthompson** [smart-on-fhir/smart-scheduling-links#7]
Right now, it seems like if you send a Location identifier, it has to be the VTrckS PIN.  I'm not sure if that is the intent or not, but could we allow for sending identifiers that are not VTrckS PINs?  

I don't know for sure, but I'm suspicious we'll see other systems want to use this spec beyond just USDS, so our implementation intends to be a little flexible regarding what identifiers are included.

**Comment by jmandel** [comment]
The intention is: if you have a VTrcks PIN, Location.identifier is where it goes.

Agreed that the current language is overly specific (i.e., doesn't explain that you can use other Identifiers too). I was kind of waiting until someone had another use case to avoid making the docs more confusing, but since you've now raised it... I'll propose a tweak.

**Comment by jmandel** [comment]
Would appreciate a quick look at #8  @cooperthompson .
